---
title: "BATS_Pigments_Hackathon"
author: "Jill Paquette"
date: "2025-08-11"
output: html_document
---

```{r}
#load in libraries
library(tidyverse)
library(lubridate)
library(viridis)
library(gridExtra)
```

```{r}
pigments = read_csv('893521_v8_bats_pigments.csv')
```

```{r}
pig = pigments %>%
  select(ID, ISO_DateTime_UTC, yyyymmdd, decy, time, Latitude, Longitude, Cruise_num, Cast, Cast_type, Bottle_number, Depth, QF_depth, p4, QF_p4, p5, QF_p5, p6, QF_p6, p7, QF_p7, p10, QF_p10, p13, QF_p13, p14, QF_p14, p19, QF_p19)
#QF_Niskin_GoFlo and QF_depth might be good to have for later
```

```{r}
#filter general dataset to be just good data in the photic zone
pig_clean = pig %>%
  filter(QF_p4 != 9 | 
           QF_p4 != 9 |
           QF_p5 != 9 |
           QF_p6 != 9 |
           QF_p7 != 9 |
           QF_p10 != 9 |
           QF_p13 != 9 |
           QF_p14 != 9 |
           QF_p19 != 9) %>%
  filter(Depth < 50) #photic zone
```

```{r}
#testing points across depths 
pig_clean_alldepth = pig %>%
  filter(QF_p4 != 9 | 
           QF_p4 != 9 |
           QF_p5 != 9 |
           QF_p6 != 9 |
           QF_p7 != 9 |
           QF_p10 != 9 |
           QF_p13 != 9 |
           QF_p14 != 9 |
           QF_p19 != 9) %>%
  mutate(year = year(ISO_DateTime_UTC)) %>%
  filter(year >= 2003) %>%
  filter(Depth < 50)

ggplot(pig_clean_alldepth, aes(x = ISO_DateTime_UTC, y = Depth)) + geom_point() + scale_y_reverse()
#y coord flip, 200 lim

#the last 5 years and top 50 m

pig_clean_200 = pig %>%
  filter(Depth < 500) %>%
  filter(QF_p4 != 9 | 
           QF_p4 != 9 |
           QF_p5 != 9 |
           QF_p6 != 9 |
           QF_p7 != 9 |
           QF_p10 != 9 |
           QF_p13 != 9 |
           QF_p14 != 9 |
           QF_p19 != 9) %>%
  mutate(year = year(ISO_DateTime_UTC)) %>%
  filter(year >= 2003) #1198

pig_clean_15 = pig %>%
    filter(QF_p4 != 9 | 
           QF_p4 != 9 |
           QF_p5 != 9 |
           QF_p6 != 9 |
           QF_p7 != 9 |
           QF_p10 != 9 |
           QF_p13 != 9 |
           QF_p14 != 9 |
           QF_p19 != 9) %>%
  mutate(year = year(ISO_DateTime_UTC)) %>%
  filter(year >= 2003) %>%
  filter(Depth < 15) #597

pig_clean_5 = pig %>%
    filter(QF_p4 != 9 | 
           QF_p4 != 9 |
           QF_p5 != 9 |
           QF_p6 != 9 |
           QF_p7 != 9 |
           QF_p10 != 9 |
           QF_p13 != 9 |
           QF_p14 != 9 |
           QF_p19 != 9) %>%
  mutate(year = year(ISO_DateTime_UTC)) %>%
  filter(year >= 2003) %>%
  filter(Depth < 5) #258

pig_clean_50 = pig %>%
    filter(QF_p4 != 9 | 
           QF_p4 != 9 |
           QF_p5 != 9 |
           QF_p6 != 9 |
           QF_p7 != 9 |
           QF_p10 != 9 |
           QF_p13 != 9 |
           QF_p14 != 9 |
           QF_p19 != 9) %>%
  mutate(year = year(ISO_DateTime_UTC)) %>%
  filter(year >= 2003) %>%
filter(Depth < 50) #1198
```

```{r}
#general dataset with just good quality data and only recent decade
pig_clean_yd = pig_clean %>%
  mutate(year = year(ISO_DateTime_UTC),
         month = month(ISO_DateTime_UTC),
         day = day(ISO_DateTime_UTC),
         yd = yday(ISO_DateTime_UTC)) %>%
  select(ID, ISO_DateTime_UTC, yyyymmdd, decy, time, month, day, year, yd, Latitude, Longitude, Cruise_num, Cast, Cast_type, Bottle_number, Depth, p4, QF_p4, p5, QF_p5, p6, QF_p6, p7, QF_p7, p10, QF_p10, p13, QF_p13, p14, QF_p14, p19, QF_p19) %>%
  filter(year >= 2003)
```

```{r}
#time series
pig_clean_ts = pig_clean_yd %>%
  group_by(ISO_DateTime_UTC) %>% 
  summarise(across(starts_with('p'), \(x) mean(x, na.rm = TRUE))) %>%
  rename(peri = p4,
         but = p5,
         fuco = p6,
         hex = p7,
         allo = p10,
         chlb = p13,
         chla = p14,
         zea = p19) %>%
  mutate(peri_mgm3 = peri*1025*0.000001,
         but_mgm3 = but*1025*0.000001,
         fuco_mgm3 = fuco*1025*0.000001,
         hex_mgm3 = hex*1025*0.000001,
         allo_mgm3 = allo*1025*0.000001,
         chlb_mgm3 = chlb*1025*0.000001,
         chla_mgm3 = chla*1025*0.000001,
         zea_mgm3 = zea*1025*0.000001) %>%
  mutate(totalDP_mgm3 = (1.41*(fuco_mgm3) + 1.41*(peri_mgm3) + 1.27*(hex_mgm3) + 0.6*(allo_mgm3) + 0.35*(but_mgm3) + 1.01*(chlb_mgm3)))

pig_clean_ts_long_mgm3 = pig_clean_ts %>%
  select(-peri, -but, -fuco, -hex, -allo, -chlb, -chla, -zea, -totalDP_mgm3, -chla_mgm3) %>%
  pivot_longer(cols = 2:8,
               names_to = 'pigment',
               values_to = 'mg/m3')
```

```{r}
#plot pigment time series)
ggplot(pig_clean_ts_long_mgm3, aes(x = ISO_DateTime_UTC, y = `mg/m3`)) + 
  geom_point(aes(color = pigment)) +
  geom_line(aes(group = pigment, color = pigment)) +
  labs(title = 'pigments mg/m3') + 
  scale_x_datetime(
    date_breaks = "2 month",       # monthly ticks
    date_labels = "%b %Y"          # e.g., "Aug 2016"
  ) + theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 4))
#add and delete chla from each to add or remove it
```

```{r}
#zooming in on heatwave 4/18-5/10 in 2024
ts_mgm3_mhw = pig_clean_ts_long_mgm3 %>%
  mutate(year = year(ISO_DateTime_UTC),
         month = month(ISO_DateTime_UTC),
         day = day(ISO_DateTime_UTC)) %>%
  filter(year == 2024) #%>%
  #filter(month == 3 | month == 4 | month == 5 | month == 6)

ggplot(ts_mgm3_mhw, aes(x = ISO_DateTime_UTC, y = `mg/m3`)) + 
  geom_point(aes(color = pigment)) +
  geom_line(aes(group = pigment, color = pigment)) +
  labs(title = 'pigments mg/m3', x = '2024') + 
  scale_x_datetime(date_breaks = '1 week',
                   date_labels = '%B %d') +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8))
```

```{r}
#pfts for ts
pfts_ts_mgm3 = pig_clean_ts %>%
  select(-peri, -but, -fuco, -hex, -allo, -chlb, -chla, -zea) %>%
  mutate(microplankton = ((1.41*(fuco_mgm3 + peri_mgm3))/totalDP_mgm3),
         diatoms = ((1.41*(fuco_mgm3))/totalDP_mgm3),
         dinoflagellates = ((1.41*(peri_mgm3))/totalDP_mgm3),
         nanoplankton = (((1.27*(hex_mgm3))+(1.01*(chlb_mgm3))+(0.35*(but_mgm3))+(0.6*(allo_mgm3)))/totalDP_mgm3),
         green_algae = ((1.01*(chlb_mgm3))),
         picoplankton = (((0.86*(zea_mgm3))+(1.27*(hex_mgm3)))/totalDP_mgm3))

pfts_ts_mgm3_long = pfts_ts_mgm3 %>%
  select(ISO_DateTime_UTC, microplankton, diatoms, dinoflagellates, nanoplankton, green_algae, picoplankton) %>% #no longer selecting fnano
  pivot_longer(cols = 2:7,
               names_to = 'pft',
               values_to = 'ratio')
```

```{r}
ggplot(pfts_ts_mgm3_long, aes(x = ISO_DateTime_UTC, y = ratio)) + 
  geom_point(aes(color = pft)) +
  geom_line(aes(group = pft, color = pft)) +
  labs(title = 'pfts time series') + 
  scale_x_datetime(date_breaks = '6 month',
                   date_labels = '%B %Y') +
  ylim(0, 1) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 6))
```

```{r}
#heatwave for pfts ts
pfts_ts_mgm3_mhw = pfts_ts_mgm3_long %>%
  mutate(year = year(ISO_DateTime_UTC),
         month = month(ISO_DateTime_UTC),
         day = month(ISO_DateTime_UTC)) %>%
  filter(year == 2024) %>%
  filter(month == 2 | month == 3 | month == 4 | month == 5 | month == 6 | month == 7)

pfts_ts_mgm3_hur = pfts_ts_mgm3_long %>%
  mutate(year = year(ISO_DateTime_UTC),
         month = month(ISO_DateTime_UTC),
         day = month(ISO_DateTime_UTC)) %>%
  filter(year == 2024) %>%
  filter(month == 6 | month == 7 | month == 8 | month == 9 | month == 10)

ggplot(pfts_ts_mgm3_mhw, aes(x = ISO_DateTime_UTC, y = ratio)) + 
  geom_point(aes(color = pft)) +
  geom_line(aes(group = pft, color = pft)) +
  labs(title = 'pfts time series - heatwave', x = '2024') + 
  scale_x_datetime(date_breaks = '3 day',
                   date_labels = '%B %d') +
  ylim(0, 1) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 6))

ggplot(pfts_ts_mgm3_hur, aes(x = ISO_DateTime_UTC, y = ratio)) + 
  geom_point(aes(color = pft)) +
  geom_line(aes(group = pft, color = pft)) +
  labs(title = 'pfts time series - hurricane', x = '2024') + 
  scale_x_datetime(date_breaks = '3 day',
                   date_labels = '%B %d') +
  ylim(0, 1) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 6))
```

```{r}
#work to create climatologies
#monthly average
pig_clean_month = pig_clean_yd %>%
  group_by(month) %>% 
  summarise(across(starts_with('p'), \(x) mean(x, na.rm = TRUE))) %>%
  rename(peri = p4,
         but = p5,
         fuco = p6,
         hex = p7,
         allo = p10,
         chlb = p13,
         chla = p14,
         zea = p19) %>%
  mutate(peri_mgm3 = peri*1025*0.000001,
         but_mgm3 = but*1025*0.000001,
         fuco_mgm3 = fuco*1025*0.000001,
         hex_mgm3 = hex*1025*0.000001,
         allo_mgm3 = allo*1025*0.000001,
         chlb_mgm3 = chlb*1025*0.000001,
         chla_mgm3 = chla*1025*0.000001,
         zea_mgm3 = zea*1025*0.000001) %>%
  mutate(totalDP_mgm3 = (1.41*(fuco_mgm3) + 1.41*(peri_mgm3) + 1.27*(hex_mgm3) + 0.6*(allo_mgm3) + 0.35*(but_mgm3) + 1.01*(chlb_mgm3)))
```

```{r}
pig_clean_month_long_mgm3 = pig_clean_month %>%
  select(-peri, -but, -fuco, -hex, -allo, -chlb, -chla, -zea) %>%
  pivot_longer(cols = 2:10,
               names_to = 'pigment',
               values_to = 'mg/m3')
```

```{r}
#pigment monthly climatology
ggplot(pig_clean_month_long_mgm3, aes(x = month, y = `mg/m3`)) + 
  geom_point(aes(color = pigment)) +
  geom_line(aes(group = pigment, color = pigment)) +
  labs(title = 'pigments mg/m3')
```

```{r}
pfts_month = pig_clean_month %>%
  select(month) %>%
  mutate() 
```

```{r}
pfts_month_long = pfts_month %>%
  select(-fnano) %>%
  pivot_longer(cols = starts_with('f'),
               names_to = 'pft',
               values_to = 'ratio')
```

```{r}
ggplot(pfts_month_long, aes(x = month, y = ratio)) + 
  geom_point(aes(color = pft)) +
  geom_line(aes(group = pft, color = pft)) +
  ylim(0, 1) +
  labs(title = 'pfts per month')
```

```{r}
#working to create daily climatology (365 days)
#daily average
pig_clean_day = pig_clean_yd %>%
  group_by(yd) %>% 
  summarise(across(starts_with('p'), \(x) mean(x, na.rm = TRUE))) %>%
  rename(peri = p4,
         but = p5,
         fuco = p6,
         hex = p7,
         allo = p10,
         chlb = p13,
         chla = p14,
         zea = p19) %>%
  mutate(peri_mgm3 = peri*1025*0.000001,
         but_mgm3 = but*1025*0.000001,
         fuco_mgm3 = fuco*1025*0.000001,
         hex_mgm3 = hex*1025*0.000001,
         allo_mgm3 = allo*1025*0.000001,
         chlb_mgm3 = chlb*1025*0.000001,
         chla_mgm3 = chla*1025*0.000001,
         zea_mgm3 = zea*1025*0.000001) %>%
  mutate(totalDP_mgm3 = (1.41*(fuco_mgm3) + 1.41*(peri_mgm3) + 1.27*(hex_mgm3) + 0.6*(allo_mgm3) + 0.35*(but_mgm3) + 1.01*(chlb_mgm3)))
```

```{r}
pig_clean_day_long_mgm3 = pig_clean_day %>%
  select(-peri, -but, -fuco, -hex, -allo, -chlb, -chla, -zea) %>%
  pivot_longer(cols = 2:10,
               names_to = 'pigment',
               values_to = 'mg/m3')
```

```{r}
#pigment daily climatology
ggplot(pig_clean_day_long_mgm3, aes(x = yd, y = `mg/m3`)) + 
  geom_point(aes(color = pigment)) +
  geom_line(aes(group = pigment, color = pigment)) +
  labs(title = 'pigments mg/m3')
```

```{r}
pfts_day = pig_clean_day %>%
  select(yd) %>%
  mutate()

#diatom equation used is S10 because all chla is lower than 2 mg/m3
```

```{r}
pfts_day_long = pfts_day %>%
  select(-fnano) %>%
  pivot_longer(cols = starts_with('f'),
               names_to = 'pft',
               values_to = 'ratio')
```

```{r}
ggplot(pfts_day_long, aes(x = yd, y = ratio)) + 
  geom_point(aes(color = pft)) +
  geom_line(aes(group = pft, color = pft)) +
  ylim(0, 1) +
  labs(title = 'pfts per day')
```

```{r}
library(maps)
library(ggrepel)
```

```{r}
#pigment on a map
world_map = map_data('world')
```

```{r}
ggplot() + 
  geom_polygon(data = world_map, aes(x = long, y = lat, group = group), fill = 'lightgray', color = 'white') +
  geom_point(data = pig_clean_yd, aes(x = Longitude, y = Latitude), size = 0.25) +
  scale_shape_manual(values = c(2, 1)) +
  coord_fixed(1.3, xlim = c(-64.5, -64), ylim = c(31, 32)) +
  labs(title = 'BATS HPLC Pigment data', x = 'Longitude', y = 'Latitude') +
  theme_minimal()
```

