---
title: "BATS_Pigments_Hackathon"
author: "Jill Paquette"
date: "2025-08-11"
output: html_document
---

```{r}
#load in libraries
library(tidyverse)
library(lubridate)
library(viridis)
library(gridExtra)
```

```{r}
pigments = read_csv('893521_v8_bats_pigments.csv')
```

```{r}
pig = pigments %>%
  select(ID, ISO_DateTime_UTC, yyyymmdd, decy, time, Latitude, Longitude, Cruise_num, Cast, Cast_type, Bottle_number, Depth, QF_depth, p4, QF_p4, p5, QF_p5, p6, QF_p6, p7, QF_p7, p10, QF_p10, p13, QF_p13, p14, QF_p14, p19, QF_p19)
#QF_Niskin_GoFlo and QF_depth might be good to have for later
```

```{r}
pig_clean = pig %>%
  filter(QF_p4 != 9 | 
           QF_p4 != 9 |
           QF_p5 != 9 |
           QF_p6 != 9 |
           QF_p7 != 9 |
           QF_p10 != 9 |
           QF_p13 != 9 |
           QF_p14 != 9 |
           QF_p19 != 9) %>%
  filter(Depth < 200) #photic zone
```

```{r}
pig_clean_yd = pig_clean %>%
  mutate(year = year(ISO_DateTime_UTC),
         month = month(ISO_DateTime_UTC),
         day = day(ISO_DateTime_UTC),
         yd = yday(ISO_DateTime_UTC)) %>%
  select(ID, ISO_DateTime_UTC, yyyymmdd, decy, time, month, day, year, yd, Latitude, Longitude, Cruise_num, Cast, Cast_type, Bottle_number, Depth, p4, QF_p4, p5, QF_p5, p6, QF_p6, p7, QF_p7, p10, QF_p10, p13, QF_p13, p14, QF_p14, p19, QF_p19) %>%
  filter(year >= 2014)
```

```{r}
#time series
pig_clean_ts = pig_clean_yd %>%
  group_by(ISO_DateTime_UTC) %>% 
  summarise(across(starts_with('p'), \(x) mean(x, na.rm = TRUE))) %>%
  rename(peri = p4,
         but = p5,
         fuco = p6,
         hexfuco = p7,
         allo = p10,
         chlb = p13,
         chla = p14,
         zea = p19) %>%
  mutate(peri_mgm3 = peri*1025*0.000001,
         but_mgm3 = but*1025*0.000001,
         fuco_mgm3 = fuco*1025*0.000001,
         hexfuco_mgm3 = hexfuco*1025*0.000001,
         allo_mgm3 = allo*1025*0.000001,
         chlb_mgm3 = chlb*1025*0.000001,
         chla_mgm3 = chla*1025*0.000001,
         zea_mgm3 = zea*1025*0.000001,
         fuco_nano_mgm3 = (hexfuco_mgm3^0.098)*(but_mgm3^1.284)) %>%
  mutate(chlaw_mgm3 = ((1.27*fuco_mgm3) + (2.43*peri_mgm3) + (1.07*hexfuco_mgm3) + (2.06*allo_mgm3) + (1.30*chlb_mgm3) + (2.36*zea_mgm3)))

pig_clean_ts_long_ngkg = pig_clean_ts %>%
  select(-peri_mgm3, -but_mgm3, -fuco_mgm3, -hexfuco_mgm3, -allo_mgm3, -chlb_mgm3, -chla_mgm3, -zea_mgm3, -fuco_nano_mgm3, -chlaw_mgm3, -chla) %>%
  pivot_longer(cols = 2:8,
               names_to = 'pigment',
               values_to = 'ng/kg')

pig_clean_ts_long_mgm3 = pig_clean_ts %>%
  select(-peri, -but, -fuco, -hexfuco, -allo, -chlb, -chla, -zea, -chlaw_mgm3, -chla_mgm3) %>%
  pivot_longer(cols = 2:9,
               names_to = 'pigment',
               values_to = 'mg/m3')
```

```{r}
ggplot(pig_clean_ts_long_ngkg, aes(x = ISO_DateTime_UTC, y = `ng/kg`)) + 
  geom_point(aes(color = pigment)) +
  geom_line(aes(group = pigment, color = pigment)) +
  labs(title = 'pigments ng/kg') + 
  scale_x_datetime(
    date_breaks = "2 month",       # monthly ticks
    date_labels = "%b %Y"          # e.g., "Aug 2016"
  ) + theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 5))
ggplot(pig_clean_ts_long_mgm3, aes(x = ISO_DateTime_UTC, y = `mg/m3`)) + 
  geom_point(aes(color = pigment)) +
  geom_line(aes(group = pigment, color = pigment)) +
  labs(title = 'pigments mg/m3') + 
  scale_x_datetime(
    date_breaks = "2 month",       # monthly ticks
    date_labels = "%b %Y"          # e.g., "Aug 2016"
  ) + theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 4))
#add and delete chla from each to add or remove it
```


```{r}
#monthly average
pig_clean_month = pig_clean_yd %>%
  group_by(month) %>% 
  summarise(across(starts_with('p'), \(x) mean(x, na.rm = TRUE))) %>%
  rename(peri = p4,
         but = p5,
         fuco = p6,
         hexfuco = p7,
         allo = p10,
         chlb = p13,
         chla = p14,
         zea = p19) %>%
  mutate(peri_mgm3 = peri*1025*0.000001,
         but_mgm3 = but*1025*0.000001,
         fuco_mgm3 = fuco*1025*0.000001,
         hexfuco_mgm3 = hexfuco*1025*0.000001,
         allo_mgm3 = allo*1025*0.000001,
         chlb_mgm3 = chlb*1025*0.000001,
         chla_mgm3 = chla*1025*0.000001,
         zea_mgm3 = zea*1025*0.000001,
         fuco_nano_mgm3 = (hexfuco_mgm3^0.098)*(but_mgm3^1.284)) %>%
  mutate(chlaw_mgm3 = ((1.27*fuco_mgm3) + (2.43*peri_mgm3) + (1.07*hexfuco_mgm3) + (2.06*allo_mgm3) + (1.30*chlb_mgm3) + (2.36*zea_mgm3))) #but is not included because it was excluded after multiple regression analyses in the losa supplement
```

```{r}
pig_clean_month_long_ngkg = pig_clean_month %>%
  select(-peri_mgm3, -but_mgm3, -fuco_mgm3, -hexfuco_mgm3, -allo_mgm3, -chlb_mgm3, -chla_mgm3, -zea_mgm3, -fuco_nano_mgm3) %>%
  pivot_longer(cols = 2:9,
               names_to = 'pigment',
               values_to = 'ng/kg')

pig_clean_month_long_mgm3 = pig_clean_month %>%
  select(-peri, -but, -fuco, -hexfuco, -allo, -chlb, -chla, -zea) %>%
  pivot_longer(cols = 2:10,
               names_to = 'pigment',
               values_to = 'mg/m3')
```

```{r}
ggplot(pig_clean_month_long_ngkg, aes(x = month, y = `ng/kg`)) + 
  geom_point(aes(color = pigment)) +
  geom_line(aes(group = pigment, color = pigment)) +
  labs(title = 'pigments ng/kg')
ggplot(pig_clean_month_long_mgm3, aes(x = month, y = `mg/m3`)) + 
  geom_point(aes(color = pigment)) +
  geom_line(aes(group = pigment, color = pigment)) +
  labs(title = 'pigments mg/m3')
```

```{r}
pfts_month = pig_clean_month %>%
  select(month) %>%
  mutate(fproka = ((2.36*pig_clean_month$zea_mgm3)/pig_clean_month$chlaw_mgm3),
         fgreenalgae = ((1.30*pig_clean_month$chlb_mgm3)/pig_clean_month$chlaw_mgm3),
         fnano = ((1.07*pig_clean_month$hexfuco_mgm3+2.06*pig_clean_month$allo_mgm3+1.30*pig_clean_month$chlb_mgm3+1.27*pig_clean_month$fuco_nano_mgm3)/pig_clean_month$chlaw_mgm3),
         fhapto = fnano-fgreenalgae,
         fdiatoms = (1.27*(pig_clean_month$fuco_mgm3-pig_clean_month$fuco_nano_mgm3))/pig_clean_month$chlaw_mgm3) 
```

```{r}
pfts_month_long = pfts_month %>%
  pivot_longer(cols = starts_with('f'),
               names_to = 'pft',
               values_to = 'ratio')
```

```{r}
ggplot(pfts_month_long, aes(x = month, y = ratio)) + 
  geom_point(aes(color = pft)) +
  geom_line(aes(group = pft, color = pft)) +
  labs(title = 'pfts per month')
```

```{r}
#daily average
pig_clean_day = pig_clean_yd %>%
  group_by(yd) %>% 
  summarise(across(starts_with('p'), \(x) mean(x, na.rm = TRUE))) %>%
  rename(peri = p4,
         but = p5,
         fuco = p6,
         hexfuco = p7,
         allo = p10,
         chlb = p13,
         chla = p14,
         zea = p19) %>%
  mutate(peri_mgm3 = peri*1025*0.000001,
         but_mgm3 = but*1025*0.000001,
         fuco_mgm3 = fuco*1025*0.000001,
         hexfuco_mgm3 = hexfuco*1025*0.000001,
         allo_mgm3 = allo*1025*0.000001,
         chlb_mgm3 = chlb*1025*0.000001,
         chla_mgm3 = chla*1025*0.000001,
         zea_mgm3 = zea*1025*0.000001,
         fuco_nano_mgm3 = (hexfuco_mgm3^0.098)*(but_mgm3^1.284)) %>%
  mutate(chlaw_mgm3 = ((1.27*fuco_mgm3) + (2.43*peri_mgm3) + (1.07*hexfuco_mgm3) + (2.06*allo_mgm3) + (1.30*chlb_mgm3) + (2.36*zea_mgm3))) #but is not included because it was excluded after multiple regression analyses in the losa supplement
```

```{r}
pig_clean_day_long_ngkg = pig_clean_day %>%
  select(-peri_mgm3, -but_mgm3, -fuco_mgm3, -hexfuco_mgm3, -allo_mgm3, -chlb_mgm3, -chla_mgm3, -zea_mgm3, -fuco_nano_mgm3) %>%
  pivot_longer(cols = 2:9,
               names_to = 'pigment',
               values_to = 'ng/kg')

pig_clean_day_long_mgm3 = pig_clean_day %>%
  select(-peri, -but, -fuco, -hexfuco, -allo, -chlb, -chla, -zea) %>%
  pivot_longer(cols = 2:10,
               names_to = 'pigment',
               values_to = 'mg/m3')
```

```{r}
ggplot(pig_clean_day_long_ngkg, aes(x = yd, y = `ng/kg`)) + 
  geom_point(aes(color = pigment)) +
  geom_line(aes(group = pigment, color = pigment)) +
  labs(title = 'pigments ng/kg')
ggplot(pig_clean_day_long_mgm3, aes(x = yd, y = `mg/m3`)) + 
  geom_point(aes(color = pigment)) +
  geom_line(aes(group = pigment, color = pigment)) +
  labs(title = 'pigments mg/m3')
```

```{r}
pfts_day = pig_clean_day %>%
  select(yd) %>%
  mutate(fproka = ((2.36*pig_clean_day$zea_mgm3)/pig_clean_day$chlaw_mgm3),
         fgreenalgae = ((1.30*pig_clean_day$chlb_mgm3)/pig_clean_day$chlaw_mgm3)) %>%
#pig_clean_day$chla_mgm3 >= 2 all results in FALSE
#pig_clean_day$chla_mgm3 > 0.08 & pig_clean_day$chla_mgm3 < 2 results in mostly TRUE some FALSE meaning I use the S6 equation for those
#pig_clean_day$chla_mgm3 <= 0.08 results in mostly FALSE with some TRUE so I use S7
  mutate(fnano = case_when(
    pig_clean_day$chla_mgm3 > 0.08 & pig_clean_day$chla_mgm3 < 2 ~ ((1.07*pig_clean_day$hexfuco_mgm3+2.06*pig_clean_day$allo_mgm3+1.30*pig_clean_day$chlb_mgm3+1.27*pig_clean_day$fuco_nano_mgm3)/pig_clean_day$chlaw_mgm3),
    pig_clean_day$chla_mgm3 <= 0.08 ~ ((12.5*pig_clean_day$chla_mgm3*1.07*pig_clean_day$hexfuco_mgm3)/pig_clean_day$chlaw_mgm3)+(((1.07*pig_clean_day$hexfuco_mgm3)+(2.06*pig_clean_day$allo_mgm3)+(1.30*pig_clean_day$chlb_mgm3))/pig_clean_day$chlaw_mgm3)+((1.27*pig_clean_day$fuco_nano_mgm3)/pig_clean_day$chlaw_mgm3)),
         fhapto = fnano-fgreenalgae,
    fdiatoms = (1.27*(pig_clean_day$fuco_mgm3-pig_clean_day$fuco_nano_mgm3))/pig_clean_day$chlaw_mgm3)

#diatom equation used is S10 because all chla is lower than 2 mg/m3
```

```{r}
pfts_day_long = pfts_day %>%
  pivot_longer(cols = starts_with('f'),
               names_to = 'pft',
               values_to = 'ratio')
```

```{r}
ggplot(pfts_day_long, aes(x = yd, y = ratio)) + 
  geom_point(aes(color = pft)) +
  geom_line(aes(group = pft, color = pft)) +
  labs(title = 'pfts per day')
#ratio is messed up
```
```{r}
library(maps)
library(ggrepel)
```

```{r}
#pigment on a map
world_map = map_data('world')
```

```{r}
ggplot() + 
  geom_polygon(data = world_map, aes(x = long, y = lat, group = group), fill = 'lightgray', color = 'white') +
  geom_point(data = pig_clean_yd, aes(x = Longitude, y = Latitude), size = 0.25) +
  scale_shape_manual(values = c(2, 1)) +
  coord_fixed(1.3, xlim = c(-70, -60), ylim = c(27, 35)) +
  labs(title = 'BATS HPLC Pigment data', x = 'Longitude', y = 'Latitude') +
  theme_minimal()
```
```

